export const REPEAT_OFFER_THRESHOLD_CENTS = 15_000_00;
export const REPEAT_OFFER_WINDOW_MS = 90 * 24 * 60 * 60 * 1000;
export const REPEAT_OFFER_PERCENT = 10;
export const REPEAT_OFFER_FLAG = 'REPEAT_OFFERS_ENABLED';
