-- 0040_learning_seed.sql
-- Initial seed for the Supplier learning center. Placeholder copy; admin can edit.
-- 4 onboarding (gated) + 4 operations (not gated).

INSERT INTO learning_lessons (id, slug, title, summary, body_markdown, track, order_index, is_published, is_required_for_publish, created_at, updated_at) VALUES
  ('lc-lesson-1','welcome-to-vyro','Welcome to Vyro','What Vyro is and how suppliers earn.','Vyro connects Sri Lankan wholesale suppliers with verified domestic and cross-border buyers. As a supplier you list products, quote RFQs, fulfill orders, and receive payouts through PayHere or bank transfer. This lesson walks through your first 7 days on Vyro and what to expect at each stage.','onboarding',1,1,1,unixepoch(),unixepoch()),
  ('lc-lesson-2','verify-your-business','Verify your business','KYC walkthrough.','Verification (KYC) confirms your business is real and trade-eligible. Upload your BR certificate, NIC of the owner, and a recent utility bill. Review takes 24 to 48 hours. While pending you can browse the dashboard but cannot publish products. Approved suppliers earn a verified badge on their storefront and rank higher in search.','onboarding',2,1,1,unixepoch(),unixepoch()),
  ('lc-lesson-3','set-up-payouts','Set up payouts','Bank account + PayHere.','Payouts cover everything you earn after orders are delivered and the buyer confirmation window closes (Net14 by default). Add a Sri Lankan bank account in LKR, or a PayHere merchant account for instant withdrawals. We hold the first payout for 7 days as a fraud precaution.','onboarding',3,1,1,unixepoch(),unixepoch()),
  ('lc-lesson-4','publish-your-first-product','Publish your first product','Listing quality bar.','A great listing has 3+ sharp photos, an accurate HS code, weight, MOQ, and a wholesale price tier. Lead time must be realistic; under-promising drives disputes. Avoid keyword stuffing; titles like "Premium A4 Paper 80gsm - 500 sheets" outperform vague ones.','onboarding',4,1,1,unixepoch(),unixepoch()),
  ('lc-lesson-5','quote-rfqs-like-a-pro','Quote RFQs like a pro','Win more quotes.','Reply within 4 hours; quotes past 24 hours are 60% less likely to convert. Lead with a clear price + MOQ + lead time, then add 2 to 3 trust signals (years in business, stock photos, prior buyer logos).','operations',1,1,0,unixepoch(),unixepoch()),
  ('lc-lesson-6','fulfillment-and-delivery-slas','Fulfillment and delivery SLAs','Hit the delivery promise.','Mark orders shipped within 24h of payment confirmation. Track every dispatch. If you cannot meet the lead time, message the buyer before the deadline - proactive comms prevent disputes.','operations',2,1,0,unixepoch(),unixepoch()),
  ('lc-lesson-7','handle-a-buyer-dispute','Handle a buyer dispute','Stay calm, respond fast.','Disputes open when a buyer reports non-delivery, damage, or quality issues. You have 48 hours to respond with evidence (photos, tracking, packing slips). Disputes that resolve by mutual agreement refund partially; resolved-by-Vyro outcomes count against your trust score.','operations',3,1,0,unixepoch(),unixepoch()),
  ('lc-lesson-8','read-your-analytics','Read your analytics','Make numbers work for you.','Your analytics page shows conversion rate, RFQ win rate, average order value, and repeat-buyer share. If conversion <2%, your listing photos or price are off. If repeat-buyer share <15%, post-delivery follow-up is missing.','operations',4,1,0,unixepoch(),unixepoch());
--> statement-breakpoint

INSERT INTO learning_quizzes (id, lesson_id, pass_threshold, created_at) VALUES
  ('lc-quiz-1','lc-lesson-1',2,unixepoch()),
  ('lc-quiz-2','lc-lesson-2',2,unixepoch()),
  ('lc-quiz-3','lc-lesson-3',2,unixepoch()),
  ('lc-quiz-4','lc-lesson-4',2,unixepoch()),
  ('lc-quiz-5','lc-lesson-5',2,unixepoch()),
  ('lc-quiz-6','lc-lesson-6',2,unixepoch()),
  ('lc-quiz-7','lc-lesson-7',2,unixepoch()),
  ('lc-quiz-8','lc-lesson-8',2,unixepoch());
--> statement-breakpoint

INSERT INTO learning_quiz_questions (id, quiz_id, order_index, prompt) VALUES
  ('lc-q-1-1','lc-quiz-1',1,'What does Vyro primarily connect?'),
  ('lc-q-1-2','lc-quiz-1',2,'Roughly how long does KYC review take?'),
  ('lc-q-1-3','lc-quiz-1',3,'What is the default payment term for buyers?'),
  ('lc-q-2-1','lc-quiz-2',1,'Which document is NOT required for KYC?'),
  ('lc-q-2-2','lc-quiz-2',2,'What happens while KYC is pending?'),
  ('lc-q-2-3','lc-quiz-2',3,'What benefit do verified suppliers get?'),
  ('lc-q-3-1','lc-quiz-3',1,'Which payout method is supported?'),
  ('lc-q-3-2','lc-quiz-3',2,'How long is the first payout held?'),
  ('lc-q-3-3','lc-quiz-3',3,'What is the default settlement currency?'),
  ('lc-q-4-1','lc-quiz-4',1,'How many photos should a strong listing have?'),
  ('lc-q-4-2','lc-quiz-4',2,'Which field is mandatory on a listing?'),
  ('lc-q-4-3','lc-quiz-4',3,'What helps a listing rank higher in search?'),
  ('lc-q-5-1','lc-quiz-5',1,'Within how many hours should you reply to an RFQ?'),
  ('lc-q-5-2','lc-quiz-5',2,'How much less likely are quotes past 24h to convert?'),
  ('lc-q-5-3','lc-quiz-5',3,'What should a quote lead with?'),
  ('lc-q-6-1','lc-quiz-6',1,'Within how many hours should orders be marked shipped?'),
  ('lc-q-6-2','lc-quiz-6',2,'What should you do if you cannot meet lead time?'),
  ('lc-q-6-3','lc-quiz-6',3,'What drives most disputes?'),
  ('lc-q-7-1','lc-quiz-7',1,'How long do you have to respond to a dispute?'),
  ('lc-q-7-2','lc-quiz-7',2,'Which evidence type is most useful?'),
  ('lc-q-7-3','lc-quiz-7',3,'What counts against your trust score?'),
  ('lc-q-8-1','lc-quiz-8',1,'What does conversion <2% suggest?'),
  ('lc-q-8-2','lc-quiz-8',2,'What does repeat-buyer share <15% suggest?'),
  ('lc-q-8-3','lc-quiz-8',3,'Which metric tracks RFQ win rate?');
--> statement-breakpoint

INSERT INTO learning_quiz_options (id, question_id, order_index, label, is_correct) VALUES
  ('lc-opt-1-1-1','lc-q-1-1',1,'Sri Lankan suppliers with domestic and cross-border buyers',1),
  ('lc-opt-1-1-2','lc-q-1-1',2,'Buyers with logistics companies',0),
  ('lc-opt-1-1-3','lc-q-1-1',3,'Banks with retail investors',0),
  ('lc-opt-1-2-1','lc-q-1-2',1,'5 minutes',0),
  ('lc-opt-1-2-2','lc-q-1-2',2,'24 to 48 hours',1),
  ('lc-opt-1-2-3','lc-q-1-2',3,'30 days',0),
  ('lc-opt-1-3-1','lc-q-1-3',1,'Net7',0),
  ('lc-opt-1-3-2','lc-q-1-3',2,'Net14',1),
  ('lc-opt-1-3-3','lc-q-1-3',3,'Net60',0),
  ('lc-opt-2-1-1','lc-q-2-1',1,'BR certificate',0),
  ('lc-opt-2-1-2','lc-q-2-1',2,'NIC of owner',0),
  ('lc-opt-2-1-3','lc-q-2-1',3,'Personal diary',1),
  ('lc-opt-2-2-1','lc-q-2-2',1,'Cannot publish products',1),
  ('lc-opt-2-2-2','lc-q-2-2',2,'Account is suspended',0),
  ('lc-opt-2-2-3','lc-q-2-2',3,'Cannot log in',0),
  ('lc-opt-2-3-1','lc-q-2-3',1,'Verified badge + ranking boost',1),
  ('lc-opt-2-3-2','lc-q-2-3',2,'Free PayHere merchant',0),
  ('lc-opt-2-3-3','lc-q-2-3',3,'No commission',0),
  ('lc-opt-3-1-1','lc-q-3-1',1,'Crypto wallet',0),
  ('lc-opt-3-1-2','lc-q-3-1',2,'Sri Lankan bank or PayHere',1),
  ('lc-opt-3-1-3','lc-q-3-1',3,'Cash on pickup',0),
  ('lc-opt-3-2-1','lc-q-3-2',1,'7 days',1),
  ('lc-opt-3-2-2','lc-q-3-2',2,'24 hours',0),
  ('lc-opt-3-2-3','lc-q-3-2',3,'Never held',0),
  ('lc-opt-3-3-1','lc-q-3-3',1,'LKR',1),
  ('lc-opt-3-3-2','lc-q-3-3',2,'USD',0),
  ('lc-opt-3-3-3','lc-q-3-3',3,'EUR',0),
  ('lc-opt-4-1-1','lc-q-4-1',1,'1 photo',0),
  ('lc-opt-4-1-2','lc-q-4-1',2,'3+ photos',1),
  ('lc-opt-4-1-3','lc-q-4-1',3,'No photos needed',0),
  ('lc-opt-4-2-1','lc-q-4-2',1,'HS code',1),
  ('lc-opt-4-2-2','lc-q-4-2',2,'Personal story',0),
  ('lc-opt-4-2-3','lc-q-4-2',3,'Favorite color',0),
  ('lc-opt-4-3-1','lc-q-4-3',1,'Keyword stuffing',0),
  ('lc-opt-4-3-2','lc-q-4-3',2,'Specific title like "A4 Paper 80gsm 500 sheets"',1),
  ('lc-opt-4-3-3','lc-q-4-3',3,'All caps',0),
  ('lc-opt-5-1-1','lc-q-5-1',1,'4 hours',1),
  ('lc-opt-5-1-2','lc-q-5-1',2,'48 hours',0),
  ('lc-opt-5-1-3','lc-q-5-1',3,'1 week',0),
  ('lc-opt-5-2-1','lc-q-5-2',1,'10%',0),
  ('lc-opt-5-2-2','lc-q-5-2',2,'60%',1),
  ('lc-opt-5-2-3','lc-q-5-2',3,'95%',0),
  ('lc-opt-5-3-1','lc-q-5-3',1,'Price + MOQ + lead time',1),
  ('lc-opt-5-3-2','lc-q-5-3',2,'Marketing tagline',0),
  ('lc-opt-5-3-3','lc-q-5-3',3,'Personal anecdote',0),
  ('lc-opt-6-1-1','lc-q-6-1',1,'24h',1),
  ('lc-opt-6-1-2','lc-q-6-1',2,'72h',0),
  ('lc-opt-6-1-3','lc-q-6-1',3,'1 week',0),
  ('lc-opt-6-2-1','lc-q-6-2',1,'Message buyer before deadline',1),
  ('lc-opt-6-2-2','lc-q-6-2',2,'Cancel silently',0),
  ('lc-opt-6-2-3','lc-q-6-2',3,'Block the buyer',0),
  ('lc-opt-6-3-1','lc-q-6-3',1,'Missed communication',1),
  ('lc-opt-6-3-2','lc-q-6-3',2,'High price',0),
  ('lc-opt-6-3-3','lc-q-6-3',3,'Too many SKUs',0),
  ('lc-opt-7-1-1','lc-q-7-1',1,'12 hours',0),
  ('lc-opt-7-1-2','lc-q-7-1',2,'48 hours',1),
  ('lc-opt-7-1-3','lc-q-7-1',3,'7 days',0),
  ('lc-opt-7-2-1','lc-q-7-2',1,'Photos of damage + tracking',1),
  ('lc-opt-7-2-2','lc-q-7-2',2,'Personal opinion essay',0),
  ('lc-opt-7-2-3','lc-q-7-2',3,'Unrelated news article',0),
  ('lc-opt-7-3-1','lc-q-7-3',1,'Resolved-by-Vyro outcomes',1),
  ('lc-opt-7-3-2','lc-q-7-3',2,'Mutual agreement',0),
  ('lc-opt-7-3-3','lc-q-7-3',3,'Buyer cancellation',0),
  ('lc-opt-8-1-1','lc-q-8-1',1,'Photos or price are off',1),
  ('lc-opt-8-1-2','lc-q-8-1',2,'Currency exchange rate',0),
  ('lc-opt-8-1-3','lc-q-8-1',3,'Weather',0),
  ('lc-opt-8-2-1','lc-q-8-2',1,'Missing post-delivery follow-up',1),
  ('lc-opt-8-2-2','lc-q-8-2',2,'Listing title too short',0),
  ('lc-opt-8-2-3','lc-q-8-2',3,'Wrong phone number',0),
  ('lc-opt-8-3-1','lc-q-8-3',1,'Conversion rate',0),
  ('lc-opt-8-3-2','lc-q-8-3',2,'RFQ win rate',1),
  ('lc-opt-8-3-3','lc-q-8-3',3,'Cart abandonment',0);