import { z } from 'zod';

export const SloQuerySchema = z.discriminatedUnion('kind', [
  z.object({ kind: z.literal('ae_sql'), sql: z.string().min(1) }),
  z.object({ kind: z.literal('d1_health') }),
  z.object({
    kind: z.literal('payment_lag'),
    maxAgeSec: z.number().int().positive(),
  }),
  z.object({
    kind: z.literal('queue_depth'),
    queue: z.enum(['audit', 'notifications', 'invoices']),
    max: z.number().int().positive(),
  }),
  z.object({
    kind: z.literal('staleness'),
    key: z.string().min(1),
    maxAgeSec: z.number().int().positive(),
  }),
]);

export const AlertChannelSchema = z.enum(['slack', 'email', 'in_app']);

export const SloRuleSchema = z.object({
  name: z.string().regex(/^[a-z][a-z0-9_.-]+$/),
  component: z.enum(['api', 'payments', 'queues', 'cron', 'web']),
  description: z.string().min(1),
  query: SloQuerySchema,
  comparator: z.enum(['gt', 'lt', 'gte', 'lte', 'eq']),
  threshold: z.number(),
  window: z.enum(['1m', '5m', '15m', '1h', '24h']),
  severity: z.enum(['info', 'warning', 'critical']),
  cooldownSec: z.number().int().positive(),
  channels: z.array(AlertChannelSchema),
  recipients: z.array(z.object({ role: z.string() })),
  escalation: z
    .object({
      severity: z.literal('critical'),
      afterSec: z.number().int().positive(),
    })
    .optional(),
  doc: z.string().optional(),
  enabled: z.boolean().default(false),
});

export type SloQuery = z.infer<typeof SloQuerySchema>;
export type AlertChannel = z.infer<typeof AlertChannelSchema>;
export type SloRule = z.infer<typeof SloRuleSchema>;

export const INITIAL_RULES: SloRule[] = [
  {
    name: 'api.error_rate_5xx',
    component: 'api',
    description: '5xx ratio above 1% over 5 minutes',
    query: {
      kind: 'ae_sql',
      sql: "SELECT CAST(COUNT_IF(CAST(status AS INT) >= 500) AS REAL) / NULLIF(COUNT(), 0) AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '5' MINUTE AND index1 = 'http'",
    },
    comparator: 'gt',
    threshold: 0.01,
    window: '5m',
    severity: 'warning',
    cooldownSec: 1800,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'ops' }],
    enabled: false,
  },
  {
    name: 'api.error_rate_5xx_critical',
    component: 'api',
    description: '5xx ratio above 5% over 5 minutes',
    query: {
      kind: 'ae_sql',
      sql: "SELECT CAST(COUNT_IF(CAST(status AS INT) >= 500) AS REAL) / NULLIF(COUNT(), 0) AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '5' MINUTE AND index1 = 'http'",
    },
    comparator: 'gt',
    threshold: 0.05,
    window: '5m',
    severity: 'critical',
    cooldownSec: 900,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'super_admin' }, { role: 'ops' }],
    enabled: false,
  },
  {
    name: 'api.p95_latency_ms',
    component: 'api',
    description: 'p95 HTTP latency above 1500ms',
    query: {
      kind: 'ae_sql',
      sql: "SELECT QUANTILE(CAST(doubles[1] AS FLOAT), 0.95) AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '5' MINUTE AND index1 = 'http'",
    },
    comparator: 'gt',
    threshold: 1500,
    window: '5m',
    severity: 'warning',
    cooldownSec: 1800,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'ops' }],
    enabled: false,
  },
  {
    name: 'd1.health',
    component: 'api',
    description: 'D1 ping failed',
    query: { kind: 'd1_health' },
    comparator: 'eq',
    threshold: 0,
    window: '1m',
    severity: 'critical',
    cooldownSec: 600,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'super_admin' }],
    escalation: { severity: 'critical', afterSec: 300 },
    enabled: false,
  },
  {
    name: 'payments.event_lag',
    component: 'payments',
    description: 'Newest payment_event older than 5 min',
    query: { kind: 'payment_lag', maxAgeSec: 300 },
    comparator: 'gt',
    threshold: 0,
    window: '15m',
    severity: 'warning',
    cooldownSec: 1800,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'finance' }],
    enabled: false,
  },
  {
    name: 'payments.reconcile_drift',
    component: 'payments',
    description: 'Reconciliation drift above 5 unmatched',
    query: { kind: 'ae_sql', sql: "SELECT 1 AS v FROM vyro_metrics WHERE 1=0" },
    comparator: 'gt',
    threshold: 5,
    window: '1h',
    severity: 'warning',
    cooldownSec: 3600,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'finance' }],
    enabled: false,
  },
  {
    name: 'queues.depth',
    component: 'queues',
    description: 'Queue backlog above 1000',
    query: {
      kind: 'queue_depth',
      queue: 'notifications',
      max: 1000,
    },
    comparator: 'gt',
    threshold: 0,
    window: '5m',
    severity: 'warning',
    cooldownSec: 1800,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'ops' }],
    enabled: false,
  },
  {
    name: 'queues.dlq',
    component: 'queues',
    description: 'DLQ events present in last 15 min',
    query: {
      kind: 'ae_sql',
      sql: "SELECT COUNT() AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '15' MINUTE AND index1 = 'queue' AND blob2 = 'dlq'",
    },
    comparator: 'gt',
    threshold: 0,
    window: '15m',
    severity: 'critical',
    cooldownSec: 900,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'ops' }, { role: 'super_admin' }],
    enabled: false,
  },
  {
    name: 'cron.last_run',
    component: 'cron',
    description: 'No sweep metrics emitted in last 24h',
    query: {
      kind: 'staleness',
      key: 'status:updated_at',
      maxAgeSec: 86400,
    },
    comparator: 'gt',
    threshold: 0,
    window: '1h',
    severity: 'warning',
    cooldownSec: 3600,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'ops' }],
    enabled: false,
  },
  {
    name: 'web.cwv_p75_lcp_ms',
    component: 'web',
    description: 'p75 LCP above 4000ms',
    query: {
      kind: 'ae_sql',
      sql: "SELECT QUANTILE(CAST(doubles[1] AS FLOAT), 0.75) AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '1' HOUR AND index1 = 'web.cwv' AND blob2 = 'lcp_ms'",
    },
    comparator: 'gt',
    threshold: 4000,
    window: '1h',
    severity: 'info',
    cooldownSec: 7200,
    channels: ['in_app'],
    recipients: [{ role: 'ops' }],
    enabled: false,
  },
  {
    name: 'sweep.stale',
    component: 'cron',
    description: 'Sweep has not updated status in 15 min',
    query: {
      kind: 'staleness',
      key: 'status:updated_at',
      maxAgeSec: 900,
    },
    comparator: 'gt',
    threshold: 0,
    window: '15m',
    severity: 'critical',
    cooldownSec: 600,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'super_admin' }],
    enabled: false,
  },
  {
    name: 'cross_border.wire_mismatch_rate',
    component: 'payments',
    description: 'Wire reconciliation mismatches above 5% of receipts over 1h',
    query: {
      kind: 'ae_sql',
      sql: "SELECT CAST(COUNT_IF(blob3 = 'yes') AS REAL) / NULLIF(COUNT(), 0) AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '1' HOUR AND index1 = 'cross_border.wire_received'",
    },
    comparator: 'gt',
    threshold: 0.05,
    window: '1h',
    severity: 'warning',
    cooldownSec: 3600,
    channels: ['slack', 'in_app'],
    recipients: [{ role: 'finance' }, { role: 'ops' }],
    doc: 'doc/cross-border.md#wire-reconciliation',
    enabled: false,
  },
  {
    name: 'cross_border.fx_unavailable_burst',
    component: 'api',
    description: 'FX snapshot failures above 3 in 5 min — provider likely down',
    query: {
      kind: 'ae_sql',
      sql: "SELECT COUNT() AS v FROM vyro_metrics WHERE timestamp > NOW() - INTERVAL '5' MINUTE AND index1 = 'cross_border.fx_unavailable'",
    },
    comparator: 'gt',
    threshold: 3,
    window: '5m',
    severity: 'critical',
    cooldownSec: 900,
    channels: ['slack', 'email', 'in_app'],
    recipients: [{ role: 'ops' }, { role: 'super_admin' }],
    doc: 'doc/cross-border.md#fx-failover',
    enabled: false,
  },
];