name = "vyro-api"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "vyro"
database_id = "41f2e2e3-29b0-4b20-8e36-92314adcf914"
migrations_dir = "../../packages/db/migrations"


[[r2_buckets]]
binding = "PRODUCTS"
bucket_name = "vyro-products"

[[kv_namespaces]]
binding = "CACHE"
id = "5a6075baf1834db294abf12405ced2b8"


[[queues.producers]]
binding = "AUDIT_QUEUE"
queue = "audit"

[[queues.producers]]
binding = "NOTIFICATIONS_QUEUE"
queue = "notifications"

[[queues.consumers]]
queue = "audit"
max_batch_size = 25
max_batch_timeout = 5

[[queues.consumers]]
queue = "notifications"
max_batch_size = 25
max_batch_timeout = 5

[[analytics_engine_datasets]]
binding = "METRICS"
dataset = "vyro_metrics"

[vars]
ENVIRONMENT = "local"
WEB_ORIGIN = "http://localhost:5173"
ADMIN_ORIGIN = "http://localhost:5174"
BETTER_AUTH_SECRET = "vyro-local-dev-secret-must-be-32-chars-long"
BETTER_AUTH_URL = "https://vyro-api.thufailahamed627.workers.dev"

[triggers]
crons = ["0 3 * * *"]

[env.production]
name = "vyro-api"

[[env.production.d1_databases]]
binding = "DB"
database_name = "vyro"
database_id = "41f2e2e3-29b0-4b20-8e36-92314adcf914"

[[env.production.r2_buckets]]
binding = "PRODUCTS"
bucket_name = "vyro-products"

[[env.production.kv_namespaces]]
binding = "CACHE"
id = "5a6075baf1834db294abf12405ced2b8"

[[env.production.queues.producers]]
binding = "AUDIT_QUEUE"
queue = "audit"

[[env.production.queues.producers]]
binding = "NOTIFICATIONS_QUEUE"
queue = "notifications"

[[env.production.queues.consumers]]
queue = "audit"
max_batch_size = 25
max_batch_timeout = 5

[[env.production.queues.consumers]]
queue = "notifications"
max_batch_size = 25
max_batch_timeout = 5

[[env.production.analytics_engine_datasets]]
binding = "METRICS"
dataset = "vyro_metrics"

[env.production.vars]
ENVIRONMENT = "production"
WEB_ORIGIN = "https://vyro-web.pages.dev"
ADMIN_ORIGIN = "https://vyro-web.pages.dev"
BETTER_AUTH_URL = "https://vyro-api.thufailahamed627.workers.dev"
